export class TranRec {

  constructor(
    public Cid: string,         // Cust/Company ID.  Differentiator in tables
    public TranDate: string,    // Date posted
    public Account: string,     // Account for this tran (bank/credit/...)
    public Category: string,
    public TranType: string,    // Deposit/Debit/Credit/Payment/Xfer/...
    public Amount: number,
    public TranExtra: string,   // Additional info about tran
    public TaxCat: string,      // Tax category (Business Expense, Business Income, Personal ..)
    public House: string,       // House associated w/tran (blank if not house specific)
    public Project: string,     // Project associated w/tran (blank if not house specific)
    public Annotation: string,  // Additional documentation about tran
    public ReconKey: string,    // Reconciliation statement that includes this tran
    public FitID: string,       // Financial Institution Unique Tran ID
    public TranId?: string,     // ID generated by Firebase
    public SplitParent?: string ) {}
}

/** Class specific to querying the transaction data base */
export class TranQ {
  /** A Transaction document query ... ALL fields optional
   * @constructor
   * @param {string} MinDate - Minimum date in yyyy-mm-dd form for querying a range of dates
   * @param {string} MaxDate - Mzximum date in yyyy-mm-dd form for querying a range of dates
   * @param {string} cid - Company ID which should be handled in the authentication code
   * @param {string[]} AccountArr - Institutional account array (bank/charge/mortgage/..)
   * @param {string[]} Category - Category on Transaction
   * @param {string[]} TranType - Type of tran (Chg/Deposit/Check/...)
   * @param {number} MinAmount - Minimum amount for a numeric range
   * @param {number} MaxAmount - Maximum amount for a numeric range
   * @param {string[]} TaxCat - Tax Category (Business expense, personal expense, ...)
   * @param {string[]} House - House tied to transaction (if any)
   * @param {string} Project - ID of project record
   * @param {string} AnnotationRegEx - Final description/annotation on tran
   */
  constructor(
    public MinDate?: string,
    public MaxDate?: string,
    public Cid?: string,
    public AccountArr?: string[],
    public Category?: string[],
    public TranType?: string[],
    public MinAmount?: number,
    public MaxAmount?: number,
    public TaxCat?: string[],
    public House?: string[],
    public Project?: string,
    public AnnotationRegEx?: string) {}
}

