export class TranRec {

  constructor(
    public Cid: string,         // Cust/Company ID.  Differentiator in tables
    public TranDate: string,    // Date posted
    public Account: string,     // Account for this tran (bank/credit/...)
    public Category: string,
    public TranType: string,    // Deposit/Debit/Credit/Payment/Xfer/...
    public Amount: number,
    public TranExtra: string,   // Additional info about tran
    public TaxCat: string,      // Tax category (Business Expense, Business Income, Personal ..)
    public House: string,       // House associated w/tran (blank if not house specific)
    public Project: string,     // Project associated w/tran (blank if not house specific)
    public Annotation: string,  // Additional documentation about tran
    public ReconKey: string,    // Reconciliation statement that includes this tran
    public FitId: string,       // Financial Institution Unique Tran ID
    public TranId?: string,
    public SplitParent?: string ) {} // ID generated by Firebase
}
